### ISSUE TITLE
How to configure the model to train on MSD datasets (Task08_HepaticVessel specifically)?

### ISSUE THREAD

**Issue by LucianoDeben** [OSUPCVLab/SegFormer3D#3]
We are interested in implementing this model architecture to our MSD segmentation task with possibly making small modifications to the model architecture itself. What do we have to change to make this work for different non cube input volumes (512, 512, 96) as MSD datasets follow the same folder structure? Nice work!

**Comment by bnavard** [comment]
Hi, in order to make the architecture for non-cubic volumes, you need to change the config. Specifically, change the `patch_kernel_size`, `patch_stride`, and `patch_padding` arguments inside the config. For example, if you have have volume of the following shape (Depth=96, Width=512, Height=512), you can have the following config: 
```
model_parameters:
    in_channels: 4
    sr_ratios: [4, 2, 1, 1]
    embed_dims: [32, 64, 160, 256]
    patch_kernel_size: [[3, 7, 7], 3, 3, 3]
    patch_stride: [[2, 4, 4], 2, 2, 2]
    patch_padding: [[1, 3, 3], 1, 1, 1]
    mlp_ratios: [4, 4, 4, 4]
    num_heads: [1, 2, 5, 8]
    depths: [2, 2, 2, 2]
    num_classes: 3
    decoder_dropout: 0.0
    decoder_head_embedding_dim: 256
```
Please note that I am defining different kernel, stride and padding for the first dimension of the input (i.e, depth).
